name: Check PR Checklist

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check if all checkboxes are checked
      run: |
        unchecked_items=$(grep -oP '\[ \]\s+\K.+' PULL_REQUEST_TEMPLATE.md || true)
        
        if [ -n "$unchecked_items" ]; then
          echo "::error::The following checklist items are unchecked:"
          echo "$unchecked_items"
          exit 1
        else
          echo "All checklist items are checked."
        fi
