name: Checklist Validation

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Check Checklist
      run: |
        # Retrieve the content of PULL_REQUEST_TEMPLATE.md
        template_url="https://api.github.com/repos/lenink18/skills-copilot-codespaces-vscode/pulls/2/files"
        checklist_content=$(curl -s $template_url | jq -r '.[] | select(.filename == "PULL_REQUEST_TEMPLATE.md") | .raw_url')
        template_content=$(curl -s $checklist_content)

        # Define the regex pattern to match checklist items
        pattern="- \[([xX\s])\] (.*)"

        # Check if each checklist item is marked as completed
        while IFS= read -r line; do
          if [[ $line =~ $pattern ]]; then
            if [[ ${BASH_REMATCH[1]} != "x" && ${BASH_REMATCH[1]} != "X" ]]; then
              echo "::error::Uncompleted checklist item: ${BASH_REMATCH[2]}"
              exit 1
            fi
          fi
        done <<< "$template_content"
