name: Check Pull Request Checklist
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check Checklist
        id: checklist
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const checklistFile = fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
            const checklistRegex = /- \[[ x]\] (.+)/g;
            const checklistMatches = checklistFile.matchAll(checklistRegex);
            let allChecked = true;
            let uncheckedItems = [];
            for (const match of checklistMatches) {
              if (!match[0].includes('[x]')) {
                allChecked = false;
                uncheckedItems.push(match[1]);
              }
            }
            if (!allChecked) {
              console.log(`Checklist items not checked: ${uncheckedItems.join(', ')}`);
              process.exit(1);
            } else {
              console.log('All checklist items are checked.{checklistFile}');
            }
