name: Check PR Checklist

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Workflow Environment
      run: |
        pwd
        ls -l
    - name: List Root Directory Contents
      run: ls -l
      
    - name: Checklist for developers
      run: |
        cat PULL_REQUEST_TEMPLATE.md
    
    - name: Check if all checkboxes are checked
      run: |
        unchecked_items=$(grep -oP '\[ \]\s+\K.+' PULL_REQUEST_TEMPLATE.md | sed '/^$/d' || true)
        
        if [ -n "$unchecked_items" ]; then
          echo "::error::The following checklist items are unchecked:"
          echo "$unchecked_items"
          exit 1
        else
          echo "All checklist items are checked."
        fi
