name: Pull Request Checklist

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR contains completed checklist
      run: |
        CHECKLIST_REGEX='\[ \]'

        if grep -q "$CHECKLIST_REGEX" ${{ github.event.pull_request.body }}; then
          echo "Checklist incomplete. Please complete all checklist items before merging."
          exit 1
        else
          echo "Checklist complete. You can proceed with merging."
        fi
