name: Check Pull Request Checklist
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check Checklist
        id: checklist
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const checklistFile = fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
            const checklistRegex = /- \[([ x])\] (.+)/g;
            let allChecked = true;
            let checkedItems = [];
            let uncheckedItems = [];
            let match;
            while ((match = checklistRegex.exec(checklistFile)) !== null) {
              const isChecked = match[1] === 'x';
              const itemText = match[2];
              if (isChecked) {
                checkedItems.push(itemText);
              } else {
                allChecked = false;
                uncheckedItems.push(itemText);
              }
            }
            if (!allChecked) {
              console.log(`Checklist items not checked:\n${uncheckedItems.join('\n')}`);
              process.exit(1);
            } else {
              console.log('All checklist items are checked:');
              console.log(checkedItems.join('\n'));
            }
