name: Checklist Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Check Checklist
      run: |
        checklist=$(select(.filename == "PULL_REQUEST_TEMPLATE.md")')
        checklist_content=$(curl -s $checklist)

        # Define the regex pattern to match checklist items
        pattern="- \[([xX\s])\] (.*)"

        # Check if each checklist item is marked as completed
        while IFS= read -r line; do
          if [[ $line =~ $pattern ]]; then
            if [[ ${BASH_REMATCH[1]} != "x" && ${BASH_REMATCH[1]} != "X" ]]; then
              echo "::error::Uncompleted checklist item: ${BASH_REMATCH[2]}"
              exit 1
            fi
          fi
        done <<< "$checklist_content"
