name: Checklist Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Check Checklist
      run: |
        # Retrieve the content of PULL_REQUEST_TEMPLATE.md
        template_url="${{ github.event.pull_request.url }}/files"
checklist_content=$(curl -s $template_url | jq -r '.[] | select(.filename == "PULL_REQUEST_TEMPLATE.md") | .raw_url')

if [[ -z $checklist_content ]]; then
  echo "::error::PULL_REQUEST_TEMPLATE.md file not found in the pull request."
  exit 1
fi

template_content=$(curl -s $checklist_content)

# Check if each checklist item is marked as completed
pattern="- \[([xX\s])\] (.*)"

while IFS= read -r line; do
  if [[ $line =~ $pattern ]]; then
    if [[ ${BASH_REMATCH[1]} != "x" && ${BASH_REMATCH[1]} != "X" ]]; then
      echo "::error::Uncompleted checklist item: ${BASH_REMATCH[2]}"
      exit 1
    fi
  fi
done <<< "$template_content"
